# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

default_image: &default_image
  docker:
    - image: circleci/node:12.12

default_resource_class: &default_resource_class
  resource_class: small

default_working_dir: &default_working_dir
  working_directory: ~/repo

defaults: &defaults
  <<: *default_image
  <<: *default_resource_class
  <<: *default_working_dir

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - restore_cache:
          keys:
            - v1-bit-envs

      - run: bit import 
      - run: bit import -e
      
      # first build may fail (when fetching compiler)
      # https://github.com/teambit/bit/issues/2297
      - run: bit build || bit build
      
      - save_cache:
          paths:
            - .git/bit/components
          key: v1-bit-envs


      # run tests!
      - run: yarn test